spring.application.name=auth-service
server.port=4005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25BbmRWYWxpZGF0aW9uMTIzNDU2Nzg5MA==


spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
