spring.application.name=billing-service

# Server port
server.port=4001

# gRPC port
grpc.server.port=9001

# Database
spring.datasource.url=jdbc:postgresql://localhost:5434/billingdb
spring.datasource.username=admin
spring.datasource.password=password

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false